### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by c4mb0t** [toddmazierski/mint-exporter#6]
I've noticed in the past few days that this script has stopped working for me. I'm guessing something changed at mint.com. 

I am getting a 404 error fetching transactionDownload.event. Here is the output:

```
/home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    from /home/c4mb0t/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:82:in `follow_redirection'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:41:in `return!'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    from /home/c4mb0t/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:82:in `follow_redirection'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:41:in `return!'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    from /home/c4mb0t/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /home/c4mb0t/.rvm/gems/ruby-1.9.3-p448/gems/rest-client-1.6.7/lib/restclient.rb:68:in `get'
    from /home/c4mb0t/reporting/mint-exporter/lib/mint.rb:31:in `csv'
    from mint-exporter.rb:12:in `<main>'
```

**Comment by zaynoon** [comment]
I just found mint-exporter and it looks perfect for my needs. I am however getting the "Access denied" HTML output instead of a .csv files 9 out of 10 times. Every now and then I get an actual csv file.
